# Generated by Django 5.2.14 on 2026-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Создан"),
                    (1, "Оплачен"),
                    (2, "В пути"),
                    (3, "Доставлен"),
                    (4, "Отменён"),
                ],
                default=0,
            ),
        ),
    ]
