# Generated by Django 5.2.14 on 2026-06-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "категорию", "verbose_name_plural": "Категории"},
        ),
    ]
